# Generated by Django 5.2 on 2025-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootlocation',
            name='country',
            field=models.CharField(default='br', max_length=80),
        ),
        migrations.AddField(
            model_name='bootlocation',
            name='country_code',
            field=models.CharField(default='br', max_length=5),
        ),
        migrations.AddField(
            model_name='bootlocation',
            name='state',
            field=models.CharField(default='br', max_length=80),
        ),
        migrations.AddField(
            model_name='favoritelocations',
            name='country',
            field=models.CharField(default='br', max_length=80),
        ),
        migrations.AddField(
            model_name='favoritelocations',
            name='country_code',
            field=models.CharField(default='br', max_length=5),
        ),
        migrations.AddField(
            model_name='favoritelocations',
            name='state',
            field=models.CharField(default='br', max_length=80),
        ),
    ]
