# Generated by Django 5.2 on 2025-07-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bootlocation_country_bootlocation_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootlocation',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='favoritelocations',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
