# Generated by Django 5.2 on 2025-07-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bootlocation_city_favoritelocations_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootlocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bootlocation',
            name='country_code',
        ),
    ]
