# Generated by Django 5.2 on 2025-07-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bootlocation_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelocations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='favoritelocations',
            name='country_code',
        ),
    ]
